on:
  workflow_dispatch:
  schedule:
    - cron: '23 3 * * *'

name: preprint-bot

jobs:
  preprint-bot:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Get preprints, post on mastodon, and write in log
        env:
          RTOOT_DEFAULT_TOKEN: ${{ secrets.COLSCI_PREPRINT_BOTSINSPACE }}
        run: |
          df <- colscibot::get_biorxiv()
          if (nrow(df) > 0) {
            colscibot::post_mastodon(df)
            df$posted <- Sys.Date()
            log <- read.csv("log.csv")
            rbind(log, df) |> 
              write.csv("log.csv", row.names = FALSE)
          }
        shell: Rscript {0}
    
      - name: Commit log
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add log.csv || echo ""
          git commit -m 'Post new preprint' || echo "No changes to commit"
          git push origin main || echo "No changes to commit"
