on:
  workflow_dispatch:
  schedule:
    - cron: '23 3 * * *'

name: preprint-bot

jobs:
  preprint-bot:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Get preprints & add to quarto listing
        run: |
          source("scripts/get_biorxiv.R")
          source("scripts/to_quarto_listing.R")
          get_biorxiv() |>
            to_quarto_listing()
        shell: Rscript {0}

      - name: Commit new preprintd
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add preprints.yaml || echo ""
          git commit -m 'Post new preprint' || echo "No changes to commit"
          git push origin main || echo "No changes to commit"

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release

      - name: Render & Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
